#!/usr/bin/env node
// Regenerate the JSON-LD block in index.html and sitemap.xml from the
// FILM / OPERATING arrays, so search engines see every project in plain HTML.
// Run after editing projects:  node tools/build_seo.js
'use strict';
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const SITE = 'https://jackabarry.com/';
const PUBLISHED = '2026-10-01';

const html = fs.readFileSync(path.join(ROOT, 'index.html'), 'utf8');
const src = html.slice(html.indexOf('const FILM = ['), html.indexOf('const CATEGORIES'));
const { FILM, OPERATING } = new Function(`${src}; return { FILM, OPERATING };`)();
global.window = {};
require(path.join(ROOT, 'palettes.js'));
const DUR = Object.fromEntries(Object.entries(window.PALETTES).map(([k, v]) => [k, v.d]));

const fmt = p => p.format.replace(', ', ' ');
const by = p => p.director === 'Various' ? '' : ` directed by ${p.director}`;
const describe = (p, operating) => operating
  ? `${fmt(p)}${by(p)} (${p.year}). Jack Barry, ${p.role.toLowerCase()}.`
  : `${fmt(p)}${by(p)} (${p.year}). Cinematography by Jack Barry.`;
const iso = s => `PT${Math.floor(s / 60)}M${Math.round(s % 60)}S`;
const person = { '@id': SITE + '#jack' };

function video(slug, name, description) {
  return {
    '@type': 'VideoObject',
    name,
    description,
    thumbnailUrl: `${SITE}media/${slug}.webp`,
    contentUrl: `${SITE}media/${slug}.hevc.mp4`,
    uploadDate: PUBLISHED,
    ...(DUR[slug] ? { duration: iso(DUR[slug]) } : {}),
  };
}

function work(p, operating) {
  const film = /short|feature/i.test(p.format) && !operating;
  const description = describe(p, operating);
  const item = {
    '@type': film ? 'Movie' : 'CreativeWork',
    name: p.title,
    dateCreated: String(p.year),
    genre: p.format,
    description,
    contributor: person,
    ...(p.director && p.director !== 'Various' ? { director: { '@type': 'Person', name: p.director } } : {}),
    ...(p.link ? { url: p.link } : {}),
    ...(p.image ? { image: p.image } : p.slug ? { image: `${SITE}media/${p.slug}.webp` } : {}),
  };
  if (p.slug) item.trailer = video(p.slug, `${p.title} trailer`, description);
  return item;
}

const graph = {
  '@context': 'https://schema.org',
  '@graph': [
    {
      '@type': 'Person',
      '@id': SITE + '#jack',
      name: 'Jack Barry',
      jobTitle: 'Cinematographer',
      hasOccupation: { '@type': 'Occupation', name: 'Director of Photography' },
      description: 'Cinematographer and director of photography based in Los Angeles and upstate New York, shooting narrative film, commercials and documentaries.',
      url: SITE,
      image: 'https://i.postimg.cc/qR1VPBw2/jack-onset-lenses.jpg',
      email: 'mailto:contact@jackabarry.com',
      telephone: '+1-518-538-6567',
      workLocation: [
        { '@type': 'Place', name: 'Los Angeles, CA' },
        { '@type': 'Place', name: 'Upstate New York' },
      ],
      knowsAbout: ['Cinematography', 'Camera operating', 'Remote head operating', 'Lighting', '16mm film'],
      sameAs: [
        'https://www.instagram.com/jackb.dop/',
        'https://www.youtube.com/@JackBarry-dop',
        'https://www.imdb.com/name/nm17324923/',
      ],
    },
    {
      '@type': 'WebSite',
      '@id': SITE + '#site',
      url: SITE,
      name: 'Jack Barry, Cinematographer',
      inLanguage: 'en',
      publisher: person,
    },
    {
      '@type': 'ProfilePage',
      '@id': SITE + '#page',
      url: SITE,
      name: 'Jack Barry | Cinematographer, Los Angeles and New York',
      isPartOf: { '@id': SITE + '#site' },
      mainEntity: person,
      primaryImageOfPage: SITE + 'media/og.jpg',
    },
    {
      '@type': 'ItemList',
      name: 'Film and documentary work',
      itemListElement: FILM.map((p, i) => ({ '@type': 'ListItem', position: i + 1, item: work(p, false) })),
    },
    {
      '@type': 'ItemList',
      name: 'Camera operating work',
      itemListElement: OPERATING.map((p, i) => ({ '@type': 'ListItem', position: i + 1, item: work(p, true) })),
    },
    video('dp-reel', 'Jack Barry cinematography reel', 'Cinematography reel of Jack Barry, director of photography.'),
    video('craft-presentation', 'How it was made: 72 Hours on Gardraxis and A Prom for the Stars', 'Jack Barry walks through the cinematography of two short films.'),
    video('away-we-go-recreation', 'Away We Go shot recreation', 'A shot-for-shot recreation from Away We Go, 2024.'),
  ],
};

const block = `<!-- seo:jsonld (generated by tools/build_seo.js) -->\n<script type="application/ld+json">\n${JSON.stringify(graph, null, 1)}\n</script>\n<!-- /seo:jsonld -->`;
const re = /<!-- seo:jsonld[\s\S]*?<!-- \/seo:jsonld -->/;
const out = re.test(html) ? html.replace(re, block) : html.replace('</head>', `${block}\n</head>`);
fs.writeFileSync(path.join(ROOT, 'index.html'), out);

// Sitemap with video extension: one page, every trailer and long-form video on it.
const esc = s => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
const vids = [
  ...FILM.filter(p => p.slug).map(p => [p.slug, `${p.title} trailer`, describe(p, false)]),
  ...OPERATING.filter(p => p.slug).map(p => [p.slug, `${p.title} trailer`, describe(p, true)]),
  ['dp-reel', 'Jack Barry cinematography reel', 'Cinematography reel of Jack Barry, director of photography.'],
  ['craft-presentation', 'How it was made: 72 Hours on Gardraxis and A Prom for the Stars', 'Jack Barry walks through the cinematography of two short films.'],
  ['away-we-go-recreation', 'Away We Go shot recreation', 'A shot-for-shot recreation from Away We Go, 2024.'],
];
const sitemap = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:video="http://www.google.com/schemas/sitemap-video/1.1">
  <url>
    <loc>${SITE}</loc>
    <lastmod>${PUBLISHED}</lastmod>
${vids.map(([slug, title, desc]) => `    <video:video>
      <video:thumbnail_loc>${SITE}media/${slug}.webp</video:thumbnail_loc>
      <video:title>${esc(title)}</video:title>
      <video:description>${esc(desc)}</video:description>
      <video:content_loc>${SITE}media/${slug}.hevc.mp4</video:content_loc>${DUR[slug] ? `\n      <video:duration>${Math.round(DUR[slug])}</video:duration>` : ''}
      <video:publication_date>${PUBLISHED}</video:publication_date>
    </video:video>`).join('\n')}
  </url>
</urlset>
`;
fs.writeFileSync(path.join(ROOT, 'sitemap.xml'), sitemap);
console.log(`JSON-LD: ${FILM.length + OPERATING.length} works; sitemap: ${vids.length} videos`);
