#!/usr/bin/env python3
"""Bundle palettes/*.json into site/palettes.js (long-form videos sampled every 2 s)."""
import json, pathlib, sys
sp = pathlib.Path(__file__).parent
out = {}
for f in sorted((sp / "palettes").glob("*.json")):
    if f.stat().st_size == 0: continue
    d = json.loads(f.read_text())
    if d["d"] > 100: d["p"] = d["p"][::2]
    out[f.stem] = d
js = "// Generated by build_palettes.py: per-second colours sampled from each video.\nwindow.PALETTES=" + json.dumps(out, separators=(",", ":")) + ";\n"
pathlib.Path(sys.argv[1]).write_text(js)
print(len(out), "palettes,", len(js), "bytes")
